name: SonarCloud
on:
  push:
    branches:
      - main
jobs:
  sonarcloud:
#    runs-on: ubuntu-16.04
    runs-on: NCSSG236NRQ3C0
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Analyze with SonarCloud
        run: ./mvnw -B verify sonar:sonar -Dsonar.projectKey=$sonar.projectKey -Dsonar.organization=$sonar.organization -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
