name: SonarCloud
on:
  push:
    branches:
      - main
jobs:
  sonarcloud:
#    runs-on: ubuntu-latest
    permissions: write-all
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Analyze with SonarCloud
#        run: ./mvnw -B verify sonar:sonar -Dsonar.projectKey=$sonar.projectKey -Dsonar.organization=$sonar.organization -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$sonar.projectKey -Dsonar.organization=$sonar.organization -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
